### ISSUE TITLE
feat: i16 types

### ISSUE THREAD

**Issue by chesedo** [shuttle-hq/synth#285]
**Required Functionality**
Currently Synth allows me to generate data for `int4` and `int8` Postgres types using the `i32` and `i64` generator. However, it is not possible to generate data for a `int2` Postgres type.

This is because [Postgres requires bytes lengths to match exactly](https://knowledge.informatica.com/s/article/135573?language=en_US). Hence the `i32` and `i64` generator cannot be used.

**Proposed Solution**
Adding an `i16` type to Synth will allow me to fill an `int2` Postgres field.

**Use case**
Filling `int2` Postgres fields

**Comment by iamwacko** [comment]
#405 is merged
