### ISSUE TITLE
Failed Compilation

### ISSUE THREAD

**Issue by iamwacko** [shuttle-hq/synth#337]
**Describe the bug**
Nightly changed it's API so ```.chain()``` is now ```.sources()```. This broke compilation. 

**To Reproduce**
1. ```cargo +nightly build --bin synth```  
2. See error
```
|
44 |         let mut chain = original.chain().collect::<Vec<_>>();
   |                                  ^^^^^ `&(dyn StdError + 'static)` is not an iterator
   |
  ::: /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/error.rs:31:1
   |
31 | pub trait Error: Debug + Display {
   | -------------------------------- doesn't satisfy `(dyn StdError + 'static): Iterator`
   |
   = note: the following trait bounds were not satisfied:
           `&(dyn StdError + 'static): Iterator`
           which is required by `&mut &(dyn StdError + 'static): Iterator`
           `(dyn StdError + 'static): Iterator`
           which is required by `&mut (dyn StdError + 'static): Iterator`
```

**Expected behavior**
Successful compilation.

**Additional context**
This can be fixed easily by changing ```.chain()``` to ```.sources()```. I will make a PR fixing this soon.

**Comment by tjni** [comment]
Is the patch in the related PR valid? I'm seeing this failure now when building `synth` using Rust 1.65.

```
   Compiling synth v0.6.8 (/private/tmp/nix-build-synth-0.6.8.drv-0/source/synth)
error[E0599]: `&(dyn StdError + 'static)` is not an iterator
  --> synth/src/error.rs:44:34
   |
44 |         let mut chain = original.chain().collect::<Vec<_>>();
   |                                  ^^^^^ `&(dyn StdError + 'static)` is not an iterator
   |
   = note: the following trait bounds were not satisfied:
           `&(dyn StdError + 'static): Iterator`
           which is required by `&mut &(dyn StdError + 'static): Iterator`
           `(dyn StdError + 'static): Iterator`
           which is required by `&mut (dyn StdError + 'static): Iterator`
```

**Comment by iamwacko** [comment]
The patch in #338 doesn't work for some unrelated reasons. I'm working on another PR, so hopefully this will be fixed in a couple hours.

**Comment by iamwacko** [comment]
Looks like this will take longer than expected, thanks to some [weird compiler errors](https://github.com/rust-lang/rust/issues/104271)

**Comment by tjni** [comment]
@iamwacko I want to acknowledge and thank you for taking the time to look into this. This is also the first time I learned about `synth`, and I love what it's aiming to do to facilitate easier testing.

**Comment by iamwacko** [comment]
@tjni Synth should work with the latest now.
