### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by iamwacko** [shuttle-hq/synth#383]
**Describe the bug**
One of the tests on .json from a tutorial is failing.

**To Reproduce**
Have the cachix github action run.

See error
```
---- docs_blog_2021_08_31_seeding_databases_tutorial_dot_md stdout ----
/build/source/synth/tmp/docs/blog/2021-08-31-seeding-databases-tutorial:224 has a JSON only code block that will be skipped
thread 'docs_blog_2021_08_31_seeding_databases_tutorial_dot_md' panicked at 'Unable to open the namespace "docs/blog/2021-08-31-seeding-databases-tutorial"

Caused by:
    0: at file docs/blog/2021-08-31-seeding-databases-tutorial/735.json
    1: Failed to parse collection
    2: expected `,` or `}` at line 4 column 38
should contain one of the following errors: {
    "unknown variant `date_time`",
}', synth/tests/docs.rs:75:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    docs_blog_2021_08_31_seeding_databases_tutorial_dot_md
```

**Expected behavior**
No error was expected. 

**Environment (please complete the following information):**
 Github Actions

**Additional context**
The only change between failing and passing was a minor change to documentation. I don't know why it fails now.

**Comment by AlexMikhalev** [comment]
cachix github action didn't run until Damien fixed permissions - this test was failing before.

**Comment by iamwacko** [comment]
The tests passed at [one point](https://github.com/shuttle-hq/synth/actions/runs/3032819495/jobs/4880629202).

**Comment by iamwacko** [comment]
I just reran the job and the test passed.

**Comment by iamwacko** [comment]
@all-contributors please add @iamwacko infra.
