### ISSUE TITLE
Support bytea column

### ISSUE THREAD

**Issue by jeenkhoorn** [shuttle-hq/synth#392]
Required Functionality
I want to use synth on a PostgreSQL DB, however, it does not feature a converter for bytea.

Proposed Solution
Implement a converter for bytea.

Use case
I want to import my database in synth, but I'm currently blocked. I'm not interested in a representative generated value for the columns, a default value would suffice.

**Comment by sanymakam** [comment]
Is this issue solved? 
I am using version `synth 0.6.9`
I am trying to connect to my postgres DB to import the schema and then generate the test data. But I am getting the below error 

`Error: We haven't implemented a converter for bytea`
Can someone please help?

**Comment by iamwacko** [comment]
> Is this issue solved? I am using version `synth 0.6.9` I am trying to connect to my postgres DB to import the schema and then generate the test data. But I am getting the below error
> 
> `Error: We haven't implemented a converter for bytea` Can someone please help?

No, this issue isn't resolved. I don't know why jeenkhoorn closed this issue, but #417 is open instead. I will try to prioritize implementing bytea, but this project isn't my entire life. Feel free to contribute though.
